import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'col-span-7',
    'col-span-8',
    'col-span-9',
    'col-span-10',
    'col-span-11',
    'col-span-12',
    'sm:col-span-1',
    'sm:col-span-2',
    'sm:col-span-3',
    'sm:col-span-4',
    'sm:col-span-5',
    'sm:col-span-6',
    'sm:col-span-7',
    'sm:col-span-8',
    'sm:col-span-9',
    'sm:col-span-10',
    'sm:col-span-11',
    'sm:col-span-12',
    'md:col-span-1',
    'md:col-span-2',
    'md:col-span-3',
    'md:col-span-4',
    'md:col-span-5',
    'md:col-span-6',
    'md:col-span-7',
    'md:col-span-8',
    'md:col-span-9',
    'md:col-span-10',
    'md:col-span-11',
    'md:col-span-12',
    'lg:col-span-1',
    'lg:col-span-2',
    'lg:col-span-3',
    'lg:col-span-4',
    'lg:col-span-5',
    'lg:col-span-6',
    'lg:col-span-7',
    'lg:col-span-8',
    'lg:col-span-9',
    'lg:col-span-10',
    'lg:col-span-11',
    'lg:col-span-12',
    'xl:col-span-1',
    'xl:col-span-2',
    'xl:col-span-3',
    'xl:col-span-4',
    'xl:col-span-5',
    'xl:col-span-6',
    'xl:col-span-7',
    'xl:col-span-8',
    'xl:col-span-9',
    'xl:col-span-10',
    'xl:col-span-11',
    'xl:col-span-12',
    '2xl:col-span-1',
    '2xl:col-span-2',
    '2xl:col-span-3',
    '2xl:col-span-4',
    '2xl:col-span-5',
    '2xl:col-span-6',
    '2xl:col-span-7',
    '2xl:col-span-8',
    '2xl:col-span-9',
    '2xl:col-span-10',
    '2xl:col-span-11',
    '2xl:col-span-12',
    'xl:grid-cols-2',
    'overflow-auto',
    'uppercase',
    'bg-purple',
    'bg-mainPurple',
    'bg-darkGrey',
    'bg-extraLightGrey',
    'border-red',
    'bg-lightPurple',
    'md:order-0',
    'md:order-1',
    'mb-2.5',
    'mt-2.5',
    'mb-6',
    'mb-8',
    'mx-auto',
    'mx-0',
    'text-shadow-lg',
    'py-9.75',
    'border-t-[0.063rem]',
    'md:border-t-0',
    'border-darkGrey',
    'border-solid',
    'lg:mx-0',
    'leading-normal',
    'md:text-[1.5rem]',
    'md:float-right',
    'md:w-[35rem]',
    'md:mb-[1.125rem]',
    'h-fit',
    'min-h-[90vh]',
    'bg-darkBlue',
    'bg-lightBlue',
    'md:pt-6.5',
    'bg-mediumPurple',
    'print:col-span-12',
    'text-[10px]',
    'text-xxs',
    'font-bold',
    'py-[1.188rem]',
    'p-[1.125rem]',
    'text-maroon',
    'md:pt-[1.625rem]',
    'md:pr-[1.875rem]',
    'md:pt-2',
    'hover:no-underline',
    'hover:text-[#902157]',
    'leading-14',
    'py-4.5',
    'my-2.5',
    'print:sm:hidden',
    'print:md:hidden',
    'print:lg:hidden',
    'print:xl:hidden',
    'print:2xl:hidden',
    'leading-[129.7%]',
    'md:mt-[2.938rem]',
    'gap-9',
    'md:h-[19.688rem]',
  ],
  theme: {
    extend: {
      screens: {
        xsm: '21.875rem',
      },
      colors: {
        white: '#ffffff',
        darkGrey: '#978F85',
        mediumGrey: '#CCCBBC',
        extraLightGrey: '#EFF0ED',
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      fontFamily: {
        arial: ['Arial', 'sans-serif'],
        font1: ['var(--font1)', 'sans-serif'],
        font2: ['var(--font2)', 'sans-serif'],
      },
    },
  },
  plugins: [],
} satisfies Config;
